### ISSUE TITLE
Can i choose the path inside my drive when i use "__google__docs"?

### ISSUE THREAD

**Issue by lincolnlemos** [yasirsiddiqui/php-google-cloud-print#10]
Can i choose the path inside my drive when i use "__google__docs"?

**Comment by yasirsiddiqui** [comment]
I didn't get your point can you elaborate?

**Comment by lemoslincoln** [comment]
Instead i use a print, i select google drive. 
> $gcp->sendPrintToPrinter('__google__docs', $file_name, $path_to_my_file, "image/jpeg");

So always images are save on google drive root. I want save inside some folders...
