### ISSUE TITLE
Automatic print without log in screen

### ISSUE THREAD

**Issue by comyou** [yasirsiddiqui/php-google-cloud-print#11]
Hello,

I am looking to implement this into an automated commerce system which I'm *trying* to get to automatically print all of the new orders by going to a webpage (www.website.com/print.php?orderid=number) which will then generate a PDF submit that to print **automatically**.

At the moment with this library I keep getting the screen asking my to choose a Google account to sign in with.
Is it possible to provide credentials within the actual library itself to bypass this login screen?

If this is possible, a brief guide would be much appreciated!

Many thanks!

**Comment by der-lukas** [comment]
You can do it with the cron.php - method! Just generate yourself an offline-key, save it to a file, get the contents with file_get_contents and send your print job to cron.php.

It's explained in the Readme, how to do this!

I actually implemented it this way in a wordpress project and it works perfectly!

**Comment by comyou** [comment]
Thank you der-lukas, 

Apparently my eyesight is diminishing as I looked over that... several times!
