### ISSUE TITLE
How can I do a server-to-server communication?

### ISSUE THREAD

**Issue by rubengc** [yasirsiddiqui/php-google-cloud-print#14]
I'm using your old class before this update (16dfd90bbec071dd634327aa5ef516ab0125b2bb)

Now, This give me an error on login, so I start to see what's the problem, and I see that now I need use Google's oAuth

So, my question is, with your new class, How can I do a server-to-server communication?

Thanks for this awesome project

**Comment by yasirsiddiqui** [comment]
You have to update to your project to Google oAuth as google now does not allow direct login. Can you explain what do you mean by server-to-server communication?

**Comment by rubengc** [comment]
I'll explain, I have an application where the customer places an order
That order is sent to the server and the server is responsible of connecting with google to print the order
OAuth have to get the access token, but, I don't want to connect to client printers, I want to connect to my own

So, How can I do this with your new classes?

**Comment by bigware** [comment]
I would recommend that new offline mode, but you have to go through the processes once, and theoretically if Google ever kills the authentication.  I did outline in a post here how you can accomplish what you are trying to do: https://github.com/yasirsiddiqui/php-google-cloud-print/issues/7
