### ISSUE TITLE
Select Printer for a print

### ISSUE THREAD

**Issue by gullsinn** [yasirsiddiqui/php-google-cloud-print#17]
i have more then one printers configured and before send it to google i want to chose which printer print job need to be sent
is it posible please

**Comment by yasirsiddiqui** [comment]
You have an array containing all available printers in example.php on line # 30. So you can choose any printer you want to send print job by using array index like 
$printerid = $printers[0]['id'];
$printerid = $printers[1]['id']; 
$printerid = $printers[2]['id'];
$resarray = $gcp->sendPrintToPrinter($printerid, "Printing Doc using Google Cloud Printing", "./pdf.pdf", "application/pdf");
