### ISSUE TITLE
Error: Cant login to google

### ISSUE THREAD

**Issue by omer414** [yasirsiddiqui/php-google-cloud-print#19]
Well i was really really excited about this service and made some tiny tweaks to the code to select printer from a dropdown etc and it worked well on my local server but once uploaded to the test server it throws an exception. (I am not sure if its due to SSL, because i dont have a certificate on my domain.)

Fatal error: Uncaught exception 'Exception' with message 'Please first login to Google' in /srv/disk6/2002385/www/cloudprint.dx.am/GoogleCloudPrint.php:121 Stack trace: #0 /srv/disk6/2002385/www/cloudprint.dx.am/example.php(30): GoogleCloudPrint->getPrinters() #1 {main} thrown in /srv/disk6/2002385/www/cloudprint.dx.am/GoogleCloudPrint.php on line 121

I had setup the configurations as described in the settings and i am also using OFFLINE as access type. But for some reason the server is not able to communicate with the app.

I also found a stackoverflow thread with the same issue with the print api. Here is the link
http://stackoverflow.com/questions/32113440/fatal-error-uncaught-exception-exception-with-message-please-first-login-to

It would be great if you could point me in the right direction.

**Comment by der-lukas** [comment]
Did you generate a new offline access token for this server or is it the same as the one you used on your local environment?

Did you add the domain in your google app?

Maybe you could try to set it up on a different server to verify if the issue is due to this server!
That's at least the things I would try! ;)

**Comment by omer414** [comment]
I haven't generated a new token its the same one that i used for local env. But i did edit the domain in the google app, as well as the config file.
Can you please confirm that you are running this code on your server without an SSL?

**Comment by yasirsiddiqui** [comment]
Can you generate new token and follow steps as mentioned in readme file?

**Comment by fuser82** [comment]
Hi, I follow all the steps in the README file but having the same error:
**Fatal error: Uncaught exception 'Exception' with message 'Please first login to Google' in GoogleCloudPrint.php on line 121**
, what could be the problem? I get to the screen where it asks permissions to connect my account with the app I created in Cloud Print... but after that it throws the error

**Comment by yasirsiddiqui** [comment]
This exception is thrown when you try to get printer list without authtoken. Can you check if you set correct redirect url in your Google app?
