### ISSUE TITLE
Offline access token

### ISSUE THREAD

**Issue by wmnf** [yasirsiddiqui/php-google-cloud-print#24]
Great plugin, thank you! No problem at all using the online option to print, but it keeps redirecting to the same example.php page and printing the sample pdf even when I point to offlineAccess.php. I printed the response array in my error log and see there is not a refresh_token being returned in the responseObj, this is the array I get in the response:

`stdClass Object
(
    [access_token] => <snip>
    [token_type] => Bearer
    [expires_in] => 3599
)
`

Can you tell me what I may be doing wrong? I see a refreshTokenConfig in Config.php, but I assume that is where I should add my refresh_token once received?

**Comment by yasirsiddiqui** [comment]
Once you get offline access token which will displayed in offlineToken.php. You need to replace this token in cron.php at line # 29. As cron.php is the offline script which can be used to print docs without user interaction.

**Comment by wmnf** [comment]
Thanks for such a quick response. My issue is I never reach offlineToken.php when I hit offlineAccess.php. Instead, it redirects to example.php and prints just like when hitting index.php.

From the looks of oAuthRedirect.php, there should be a refersh_token in the response from Google, but there is not, only an access_token returned and it continues to redirect to example.php instead of offlineToken.php?offlinetoken=".$responseObj->refresh_token. Anyway, I did take the access_token returned from Google and entered into cron.php as you suggested, is that all that need to be done? That does seem to work when hitting cron.php.

**Comment by yasirsiddiqui** [comment]
If hitting cron.php prints doc that means your offline access token is correct and you have put it in the right place in cron.php

**Comment by jesusmisael** [comment]
Saludos.
La solución  es que debes revocar la autorización de la aplicación ya que se genera el refresh_token solo una vez, cuando se da el permiso por primera vez para acceder a la aplicación. 
Si accedes otra vez pero el acceso no esta revocado, no regresara refresh_token
Encontré esta solución en este link http://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token
Esta es la respuesa que ofrece el usuario de stackoverflow
The refresh_token is only provided on the first authorization from the user. Subsequent authorizations, such as the kind you make while testing an OAuth2 integration, will not return the refresh_token again.
- Go to your account security settings: https://www.google.com/settings/u/1/security.
- Click the edit button next to "Authorizing applications and sites".
- Then click "Revoke Access" next to your app.
- The next OAuth2 request you make will return a refresh_token.

**Comment by vairafiq** [comment]
I am trying to get the offlineToken but I failed to find out the token. Please help me, I am new to google APIs.

**Comment by dele** [comment]
Hello, I hit offlineAccess.php after that i get redirect to oAuthRedirect.php and i made print_r($responseObj); die;


And i see. https://prnt.sc/qrtzin


And no in arrray refresh_token what is the problem?

**Comment by dele** [comment]
I found a solution.

in config must be added

    $offlineAccessConfig = array(
        'access_type' => 'offline',  
        "approval_prompt"    => "force",
    );

https://stackoverflow.com/questions/35009429/google-api-refresh-token-missing-access-type-offline
