### ISSUE TITLE
offline access and example not working.

### ISSUE THREAD

**Issue by emildd** [yasirsiddiqui/php-google-cloud-print#28]
I just access offline access and exampe.php and output like this

Fatal error: Uncaught exception 'Exception' with message 'Please first login to Google' in /Applications/XAMPP/xamppfiles/htdocs/cloudprint/GoogleCloudPrint.php:121 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/cloudprint/example.php(29): GoogleCloudPrint->getPrinters() #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/cloudprint/GoogleCloudPrint.php on line 121

**Comment by znvl** [comment]
Very same here!

**Comment by yasirsiddiqui** [comment]
The offline access token is only provided on the first authorization from the user. Subsequent authorizations, such as the kind you make while testing an OAuth2 integration, will not return the refresh_token again.

**Comment by emildd** [comment]
Thank you @znvl it's worked for me. 

@yasirsiddiqui for online access, can I use the way at above? and possible to implement at hosting server as a client access?

**Comment by eelke** [comment]
@yasirsiddiqui It would be helpful if you could write update the README to reflect the need to revoke access.

**Comment by ruebenacker** [comment]
Use 'approval_prompt' => 'force' in offlineAccessConfig
