### ISSUE TITLE
No access token

### ISSUE THREAD

**Issue by itsoulos** [yasirsiddiqui/php-google-cloud-print#31]
Dear sir,
I have installed your library to my server but it can not get any access token 
from google
The following code:
$printers = $gcp->getPrinters();
print_r($printers);
does not print anything and $_SESSION['accessToken'] is empty
What should I do?

best regards,
Giannis

**Comment by itsoulos** [comment]
Also in Google Chrome I am getting the following error HTTP ERROR 500

**Comment by itsoulos** [comment]
after some changes in example.php I get the following error
Fatal error: Uncaught exception 'Exception' with message 'Please first login to Google' in /var/www/vhosts/opensofthellas.gr/httpdocs/google_cloud/GoogleCloudPrint.php:126 Stack trace: #0 /var/www/vhosts/opensofthellas.gr/httpdocs/google_cloud/example.php(32): GoogleCloudPrint->getPrinters() #1 {main} thrown in /var/www/vhosts/opensofthellas.gr/httpdocs/google_cloud/GoogleCloudPrint.php on line 126

**Comment by luisjaviercr** [comment]
I have the same problem any suggested solution ?

**Comment by yasirsiddiqui** [comment]
Can you make sure you follow all the steps in readme?

**Comment by luisjaviercr** [comment]
yes i´m sure, Iam tring to convert this to a codeigniter library for a private project any recomendations? thanks in advance.
