### ISSUE TITLE
Printing pdf from url?

### ISSUE THREAD

**Issue by solosimpi** [yasirsiddiqui/php-google-cloud-print#4]
Hello sry for my ver bad english.
Your class is awesome, only a question It´s posible to print from a pdf that´s accesible from web, for example: www.mydomain.com/pdf-to-print.pdf ??

**Comment by yasirsiddiqui** [comment]
I guess you can pass web url to the sendPrintToPrinter() and it should fetch the file but i have not tested that yet.

**Comment by rx350h** [comment]
Sorry, for my english, but can You help me, what i should to do if i want to print "URL"? I'm newbie in PHP, I want to print from "URL" without downloading and saving.

**Comment by rx350h** [comment]
$resarray = $gcp->sendPrintToPrinter($printerid, "Printing Doc using Google Cloud Printing", "www.google.com/landing/cloudprint/testpage.pdf", "url"); it does not work

**Comment by yasirsiddiqui** [comment]
See this in php documentation about fopen

If PHP has decided that filename specifies a registered protocol, and that protocol is registered as a network URL, PHP will check to make sure that allow_url_fopen is enabled. If it is switched off, PHP will emit a warning and the fopen call will fail.

Can you try replacing 
$handle = fopen($filepath, "rb"); with $handle = fopen($filepath, "r");
in GoogleCloudPrint.php

**Comment by rx350h** [comment]
i think it will be helpful, so in GoogleCloudPrint.php 
                        $post_fields = array(				
			'printerid' => $printerid,
			'title' => $printjobtitle,
                        'path' => $filepath,
                        'ticket' => "{\"version\": \"1.0\",\"print\": {}}",
			'content' => $filepath, 
			'contentType' => "url"		
		                                        );
Where $filepath it's URL like www.example/text.txt, however it was sent to jobs

**Comment by easyml9** [comment]
I've made the changes to the config.php file as described, but when I load the index.php page it redirects to oAuthRedirect.php? and only shows a blank page.
