### ISSUE TITLE
Refresh Token Expires problem

### ISSUE THREAD

**Issue by krystian-rzepa** [yasirsiddiqui/php-google-cloud-print#40]
Hi, I generate an access key, everything works, but it expires after about 30 minutes. I want to use this as a cron for printing every few hours so I want to set the key expiration for e.g. 1 year. I found something like this: https://cloud.google.com/apigee/docs/api-platform/antipatterns/oauth-long-expiration but i don't know how to apply it. Thanks for your help in advance.

**Comment by yasirsiddiqui** [comment]
For Offline Access (when you want to send prints without user presence) hit offlineAccess.php

I would recommend that new offline mode, but you have to go through the processes once, and theoretically if Google ever kills the authentication.

**Comment by krystian-rzepa** [comment]
> For Offline Access (when you want to send prints without user presence) hit offlineAccess.php
> 
> I would recommend that new offline mode, but you have to go through the processes once, and theoretically if Google ever kills the authentication.

I hit offlineAccess.php, I made a authentication, replaced token in drukowanie.php (my copy of cron.php file), but after about 30min-1h a get an arror: Fatal error: Uncaught Exception: Please first login to Google in /www/wwwroot/test-site/drukowanie/GoogleCloudPrint.php:123 Stack trace: #0 /www/wwwroot/test-site/drukowanie/drukowanie.php(48): GoogleCloudPrint->getPrinters() #1 {main} thrown in /www/wwwroot/test-site/drukowanie/GoogleCloudPrint.php on line 123

**Comment by krystian-rzepa** [comment]
https://stackoverflow.com/questions/63710145/cloudprint-php-refresh-token-expires-problem
