### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by easyml9** [yasirsiddiqui/php-google-cloud-print#5]
I've made the changes to the config.php file as described, but when I load the index.php page it redirects to oAuthRedirect.php? and only shows a blank page.

**Comment by yasirsiddiqui** [comment]
Can you check for php errors by putting this code to the beginning of index,php? May be there is syntax error.
error_reporting(E_ALL);

**Comment by easyml9** [comment]
I did try error_reporting(E_ALL) in the index.php and oAuthRedirect.php 

Just getting a blank page under (http://example.com/oAuthRedirect.php?) after redirect

**Comment by yasirsiddiqui** [comment]
What Redirect URIs you entered when creating Google API project in Google developer console?
Redirect URIs should point to oAuthRedirect.php on your server.
Also Can you paste query string for the oAuthRedirect.php? I guess it is missing some arguments in query string.
