### ISSUE TITLE
PaperSize

### ISSUE THREAD

**Issue by lincolnlemos** [yasirsiddiqui/php-google-cloud-print#6]
How we can set paperSize?
I search this on https://developers.google.com/cloud-print/docs but not found how integrate this...

**Comment by yasirsiddiqui** [comment]
You can follow the links below to see it printer preferences work
http://www.phpclasses.org/discuss/package/8086/thread/4/
https://developers.google.com/cloud-print/docs/appInterfaces#submit
https://developers.google.com/cloud-print/docs/cdd#cjt

**Comment by comyou** [comment]
Sorry to jump on this but it seemed better than creating a new one.

I've tried setting my ticket settings as the following
"{"version": "1.0","print": {"media_size" : { "width_microns" : 72000, "height_microns" : 297000}}}"

Which, as far I can see should set the size to 72*297mm (which is the size my printer says in its capabilities doing https://www.google.com/cloudprint/printer) yet it looks like it is printing in A4 size and only printing a section the width of the paper from the center of the A4.

Have I missed something in my ticket settings?

**Comment by yasirsiddiqui** [comment]
@lemoslincoln @comyou any luck with setting paper size?

**Comment by lemoslincoln** [comment]
nops!

*Lincoln Lemos*
www.bigodesign.com.br

62 8275 0010
62 3932 7441



2015-08-11 11:41 GMT-03:00 Yasir Siddiqui <notifications@github.com>:

**Comment by der-lukas** [comment]
@lemoslincoln have you tried what I suggested in the other thread? https://github.com/yasirsiddiqui/php-google-cloud-print/issues/16#issuecomment-129938138
