### ISSUE TITLE
I cant get the example Working

### ISSUE THREAD

**Issue by bigware** [yasirsiddiqui/php-google-cloud-print#8]
So Google turned off the old method today, so I'm left scrambling to implement the new version. I installed a demo here: http://googlecloudprint.shirtstop.us but keep getting:

Fatal error: Uncaught exception 'Exception' with message 'Please first login to Google' in ......./GoogleCloudPrint.php:80 Stack trace: #0 ......./example.php(30): GoogleCloudPrint->getPrinters() #1 {main} thrown in ......./GoogleCloudPrint.php on line 80

**Comment by yasirsiddiqui** [comment]
I think you have not configured it properly. In Google Developer Console when creating new client 
Authorized redirect URIs should point to oAuthRedirect.php on your server.
Login to Developer Console and click on Credentials in the left menu and then click Edit Settings button.
A popup will appear in Authorized redirect URIs text area enter url that should point to 
oAuthRedirect.php on your server.
![snapshot25](https://cloud.githubusercontent.com/assets/3072536/7853837/b9d6e4b8-052c-11e5-84a7-6e72748d1b99.png)

**Comment by bigware** [comment]
Thanx for your quick reply. I made sure that was correct already.

![image2](https://cloud.githubusercontent.com/assets/5322860/7854072/d750df6a-04e3-11e5-8bcf-63107ec8064d.png)

**Comment by yasirsiddiqui** [comment]
Did you replace redirect_uri to point to oAuthRedirect.php on your server in $redirectConfig and $authConfig arrays in Config.php?

**Comment by bigware** [comment]
Yup.
![image3](https://cloud.githubusercontent.com/assets/5322860/7854221/506ab988-04e5-11e5-92e7-bc1478d95b07.png)

**Comment by yasirsiddiqui** [comment]
well redirect_uri in $authConfig array is wrong see "phpp" at the end of line. Can you fix that and try again.

**Comment by bigware** [comment]
Seems to be working now. Wow. I've been knocking myself all day trying to figure out the issue. Thanx for your help.
