### ISSUE TITLE
'Please first login to Google'

### ISSUE THREAD

**Issue by juliangums** [yasirsiddiqui/php-google-cloud-print#9]
I tried it about 3 weeks ago and it was working fine. But nowsuddently it stopped working. What's the problem? Google credentials are still the same and should be working.

Fatal error: Uncaught exception 'Exception' with message 'Please first login to Google' in /homepages/14/d519345690/htdocs/bar/print/GoogleCloudPrint.php:120 Stack trace: #0 /homepages/14/d519345690/htdocs/bar/print/example.php(30): GoogleCloudPrint->getPrinters() #1 {main} thrown in /homepages/14/d519345690/htdocs/bar/print/GoogleCloudPrint.php on line 120

**Comment by bigware** [comment]
You have to update the version. Google no longer accepts raw username and passwords.

**Comment by juliangums** [comment]
i downloaded the new version

**Comment by bigware** [comment]
Check out the readme and demo. The log in system totally changed.

**Comment by juliangums** [comment]
i did it exactly like in the readme. i changed the client id, secret and the url to the oAuthRedirect.php.
still it doesn't work. i wanna cry xD

**Comment by juliangums** [comment]
i've got the newest version, just redownloaded and reinstalled 10 minutes ago.
i created a new client id with google just a few minutes ago. i changed everything like in the readme. it does not work. does it work with you?

**Comment by bigware** [comment]
Yes, it works for me. Do you get an auth code from google?

**Comment by juliangums** [comment]
strange... how do i check the auth code? i don't think so, as the message actually only appears if the authtoken is empty. i just get the error message if i open the example.php. i just redid everything with a new google account and new credentials. no success...

**Comment by bigware** [comment]
Try the offline method.

**Comment by juliangums** [comment]
that works :+1:
